# Generated by Django 5.2.5 on 2025-08-07 07:44

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(default="", unique=True)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("class_datetime", models.DateTimeField()),
                (
                    "attendance_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance_photos/"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.department",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.subject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prn", models.BigIntegerField(unique=True)),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.TextField()),
                ("year", models.IntegerField()),
                (
                    "face_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
                ("notification_token", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField()),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.classsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAttendancePercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subjectAttendancePercentage",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectFromDept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.department",
                    ),
                ),
                ("subject", models.ManyToManyField(to="Home.subject")),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.TextField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.student"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.teacher"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classsession",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Home.teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=200,
                fields=["face_embedding"],
                m=16,
                name="student_face_embedding_idx",
                opclasses=["vector_l2_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("class_session", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectfromdept",
            unique_together={("department", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "subject")},
        ),
    ]
